### ISSUE TITLE
 check_mysql_query segfaults with mysql-connector-c // __rawmemchr_avx2

### ISSUE THREAD

**Issue by internethering** [monitoring-plugins/monitoring-plugins#1562]
Hi, Gentoo switched from mysql shipped client libs to mysql-connector-c (https://dev.mysql.com/downloads/connector/c/):

```               PID: 22833 (check_mysql_que)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Thu 2018-11-15 14:54:09 CET (1s ago)
  Command Line: /usr/lib64/nagios/plugins/check_mysql_query -q SELECT CASE WHEN variable_value = 'ON' THEN 0 ELSE 2 END FROM information_schema.global_status WHERE variable_name='SLAVE_RUNNING' -u munin -w 0 -c 1
    Executable: /usr/lib64/nagios/plugins/check_mysql_query
 Control Group: /user.slice/user-1000.slice/session-586.scope
          Unit: session-586.scope
         Slice: user-1000.slice
       Session: 586
     Owner UID: 1000 (rhering)
       Boot ID: 1402b547b1f842789ffb300c29f0e707
    Machine ID: 4a6906c2152dff421b9b5a385455c64e
      Hostname: alpha.mail
       Storage: /var/lib/systemd/coredump/core.check_mysql_que.0.1402b547b1f842789ffb300c29f0e707.22833.1542290049000000.lz4
       Message: Process 22833 (check_mysql_que) of user 0 dumped core.
                
                Stack trace of thread 22833:
                #0  0x00007f5713962613 __rawmemchr_avx2 (libc.so.6)
                #1  0x00007f5713881192 _IO_str_init_static_internal (libc.so.6)
                #2  0x00007f57138713fd _IO_vsscanf (libc.so.6)
                #3  0x00007f571386a97c __sscanf (libc.so.6)
                #4  0x0000562cb8f462e8 is_numeric (check_mysql_query)
                #5  0x0000562cb8f4562a main (check_mysql_query)
                #6  0x00007f571381eae7 __libc_start_main (libc.so.6)
                #7  0x0000562cb8f45a1a _start (check_mysql_query)

GNU gdb (Gentoo 8.2 p1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib64/nagios/plugins/check_mysql_query...Reading symbols from /usr/lib64/debug//usr/lib64/nagios/plugins/check_mysql_query.debug...done.
done.

warning: core file may not match specified executable file.
[New LWP 22833]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/lib64/nagios/plugins/check_mysql_query -q SELECT CASE WHEN variable_value'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __rawmemchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:61
61              VPCMPEQ (%rdi), %ymm0, %ymm1
(gdb) bt
#0  __rawmemchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:61
#1  0x00007f5713881192 in _IO_str_init_static_internal (sf=sf@entry=0x7ffe11c4a2d0, ptr=ptr@entry=0x8f8f8f8f8f8f8f8f <error: Cannot access memory at address 0x8f8f8f8f8f8f8f8f>, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007f57138713fd in _IO_vsscanf (string=0x8f8f8f8f8f8f8f8f <error: Cannot access memory at address 0x8f8f8f8f8f8f8f8f>, format=0x562cb8f4ca54 "%f%c", args=args@entry=0x7ffe11c4a400) at iovsscanf.c:40
#3  0x00007f571386a97c in __sscanf (s=<optimized out>, format=format@entry=0x562cb8f4ca54 "%f%c") at sscanf.c:32
#4  0x0000562cb8f462e8 in is_numeric (number=<optimized out>) at utils.c:186
#5  0x0000562cb8f4562a in main (argc=<optimized out>, argv=<optimized out>) at check_mysql_query.c:149
```

I got this problem fixed with the attached patch:

[mysql-connector.patch.txt](https://github.com/monitoring-plugins/monitoring-plugins/files/2585568/mysql-connector.patch.txt)

some version info:
dev-db/mysql-connector-c: 6.1.11-r1
dev-db/mysql: 5.7.23-r2
net-analyzer/monitoring-plugins: 2.2-r3

**Comment by waja** [comment]
@internethering: can you please be so kind and turn that into an PR? Thanks!
