### ISSUE TITLE
perfdata segfaults with (u)int64_t on 32-bit machines (check_disk)

### ISSUE THREAD

**Issue by andreasbaumann** [monitoring-plugins/monitoring-plugins#1799]
For instance on a IA-32 or armv7 distribution I get with:

```
./check_disk -w 10% -c 20% -p /
Segmentation fault (core dumped)
```

Inspecting the trace I see:

```
Program received signal SIGSEGV, Segmentation fault.
0xf7e504bf in strlen () from /usr/lib/libc.so.6
(gdb) bt 
#0  0xf7e504bf in strlen () from /usr/lib/libc.so.6
#1  0xf7e0c7d9 in ?? () from /usr/lib/libc.so.6
#2  0xf7e29c6b in ?? () from /usr/lib/libc.so.6
#3  0xf7e29d5a in vasprintf () from /usr/lib/libc.so.6
#4  0x5655b046 in xvasprintf (ap=0xffffd9d8 "\200\243VV", fmt=0x565628cd "%s=%ld%s;", strp=0xffffda28)
    at utils.c:539
#5  xasprintf (strp=0xffffda28, fmt=0x565628cd "%s=%ld%s;") at utils.c:551
#6  0x5655b323 in perfdata_uint64 (label=0x5656a380 "/", val=27149729792, uom=0x56561288 "B", warnp=1, 
    warn=30150859161, critp=1, crit=26800763699, minp=1, minv=0, maxp=1, maxv=33500954624)
    at utils.c:620
#7  0x5655a3b6 in main (argc=<optimized out>, argv=<optimized out>) at check_disk.c:356
(gdb)
```

The problem is using %ld directly instead of the "beautiful" PRId64 and PRIu64 macros. :-)

I'll make a pull request..

**Comment by andreasbaumann** [comment]
https://github.com/monitoring-plugins/monitoring-plugins/pull/1800

**Comment by andreasbaumann** [comment]
Just for completeness: the segfault happened with glibc 2.36 on ArchlinuxARM (armv7) and on Archlinux32..

**Comment by RincewindsHat** [comment]
Merged

**Comment by andreasbaumann** [comment]
#1802
